# Generated by Django 3.1.2 on 2020-10-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'verbose_name': 'Todos'},
        ),
    ]
