# Generated by Django 3.1.2 on 2020-10-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20201015_0646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'verbose_name': 'Todos', 'verbose_name_plural': 'todos'},
        ),
    ]
