# Generated by Django 3.1.2 on 2020-10-21 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_auto_20201015_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='auth.user'),
            preserve_default=False,
        ),
    ]
